class Spell:



  async def Iterate(self):
    myMsg = ""
    for aSpell in self.list:
      #print(aSpell)
      #print(self.list[aSpell].keys())
      myClass = self.list[aSpell]["Class"]
      myLevel = self.list[aSpell]["Level"]
      myName = self.list[aSpell]["Name"]
      myEra = self.list[aSpell]["Era"]
      howToGet = await self.Preferred(aSpell)

      thisMsg = "{} ({}): {} ({}) - {}".format(myClass, myLevel, myName, myEra, howToGet) 
      
      myMsg += "{}\r".format(thisMsg)

      if howToGet == "TBD":
        print(thisMsg)
    
      

      
      
  #,"Bard_Chant of Battle" : {"Class" : "Bard", "Level" : "1", "Name" : "Chant of Battle", "Mana" : "0", "Skill" : "Percussion_instruments", "Target Type" : "Group", "Era" : "Classic", "PoK Vendor" : "Minstrel Joet", "Turn In" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
  async def Preferred(self, pSpell):


    #'Class', 'Level', 'Name', 'Mana', 'Skill', 'Target Type', 'Era', 'PoK Vendor', 'Turn In', 'Quest URL', 'Drop  URL', 'Research URL'

    if len(self.list[pSpell]['PoK Vendor']) > 0:
      myReturn = "PoK {}".format(self.list[pSpell]['PoK Vendor'])
      return myReturn
    if len(self.list[pSpell]['Turn In']) > 0:
      myReturn = "Turn In {}".format(self.list[pSpell]['Turn In'])
      return myReturn
    if len(self.list[pSpell]['Quest URL']) > 0:
      myReturn = "Quest {}".format(self.list[pSpell]['Quest URL'])
      return myReturn
    if len(self.list[pSpell]['Drop  URL']) > 0:
      myReturn = "Drop {}".format(self.list[pSpell]['Drop  URL'])
      return myReturn
    if len(self.list[pSpell]['Research URL']) > 0:
      myReturn = "Research {}".format(self.list[pSpell]['Research URL'])
      return myReturn
    if len(self.list[pSpell]['Vendor URL']) > 0:
      myReturn = "Research {}".format(self.list[pSpell]['Vendor URL'])
      return myReturn
    else:
      return "TBD"



  def __init__(self):
    self.list = {
#=CONCATENATE(",""",A2,"_",C2,""" : {""Class"" : """, A2, """, """,B$1, """ : """,B2,""", """,C$1, """ : """,C2,""", """,D$1, """ : """,D2,""", """,E$1, """ : """,E2,""", """,F$1, """ : """,F2,""", """,G$1, """ : """,G2,""", """,H$1, """ : """,H2,""", """,I$1, """ : """,I2,""", """,K$1, """ : """,K2,""", """,L$1, """ : """,L2,""", """,M$1, """ : """,M2,"""}")

#=CONCATENATE(",""",A2,"_",C2,""" : {""Class"" : """, A2, """, """,B$1, """ : """,B2,""", """,C$1, """ : """,C2,""", """,D$1, """ : """,D2,""", """,E$1, """ : """,E2,""", """,F$1, """ : """,F2,""", """,G$1, """ : """,G2,""", """,H$1, """ : """,H2,""", """,I$1, """ : """,I2,""", """,J$1, """ : """,J2,""", """,K$1, """ : """,K2,""", """,L$1, """ : """,L2,""", """,M$1, """ : """,M2,"""}")


"Bard_Chant of Battle" : {"Class" : "Bard", "Level" : "1", "Name" : "Chant of Battle", "Mana" : "0", "Skill" : "Percussion_instruments", "Target Type" : "Group", "Era" : "Classic", "PoK Vendor" : "Minstrel Joet", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Chords of Dissonance" : {"Class" : "Bard", "Level" : "2", "Name" : "Chords of Dissonance", "Mana" : "0", "Skill" : "Stringed_instruments", "Target Type" : "Area of effect around the caster", "Era" : "Classic", "PoK Vendor" : "Minstrel Joet", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Jaxan`s Jig o` Vigor" : {"Class" : "Bard", "Level" : "3", "Name" : "Jaxan`s Jig o` Vigor", "Mana" : "0", "Skill" : "Percussion_instruments", "Target Type" : "Group", "Era" : "Classic", "PoK Vendor" : "Minstrel Joet", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Lyssa`s Locating Lyric" : {"Class" : "Bard", "Level" : "4", "Name" : "Lyssa`s Locating Lyric", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Self only", "Era" : "Classic", "PoK Vendor" : "Minstrel Joet", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Selo`s Accelerando" : {"Class" : "Bard", "Level" : "5", "Name" : "Selo`s Accelerando", "Mana" : "0", "Skill" : "Percussion_instruments", "Target Type" : "Group", "Era" : "Classic", "PoK Vendor" : "Minstrel Joet", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Hymn of Restoration" : {"Class" : "Bard", "Level" : "6", "Name" : "Hymn of Restoration", "Mana" : "0", "Skill" : "Stringed_instruments", "Target Type" : "Group", "Era" : "Classic", "PoK Vendor" : "Minstrel Joet", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Jonthan's Whistling Warsong" : {"Class" : "Bard", "Level" : "7", "Name" : "Jonthan's Whistling Warsong", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Self only", "Era" : "Classic", "PoK Vendor" : "Minstrel Joet", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Kelin`s Lugubrious Lament" : {"Class" : "Bard", "Level" : "8", "Name" : "Kelin`s Lugubrious Lament", "Mana" : "0", "Skill" : "Stringed_instruments", "Target Type" : "Single target", "Era" : "Classic", "PoK Vendor" : "Minstrel Gwiar", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Elemental Rhythms" : {"Class" : "Bard", "Level" : "9", "Name" : "Elemental Rhythms", "Mana" : "0", "Skill" : "Percussion_instruments", "Target Type" : "Group", "Era" : "Classic", "PoK Vendor" : "Minstrel Cirsaelle", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Magical Monologue" : {"Class" : "Bard", "Level" : "9", "Name" : "Magical Monologue", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Self only", "Era" : "Luclin", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "https://allaclone.wayfarershaven.com/?a=item&id=7701", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Anthem de Arms" : {"Class" : "Bard", "Level" : "10", "Name" : "Anthem de Arms", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Group", "Era" : "Classic", "PoK Vendor" : "Minstrel Silnon", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Cinda`s Charismatic Carillon" : {"Class" : "Bard", "Level" : "11", "Name" : "Cinda`s Charismatic Carillon", "Mana" : "0", "Skill" : "Wind_instruments", "Target Type" : "Single target", "Era" : "Classic", "PoK Vendor" : "Minstrel Gwiar", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Brusco`s Boastful Bellow" : {"Class" : "Bard", "Level" : "12", "Name" : "Brusco`s Boastful Bellow", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Single target", "Era" : "Classic", "PoK Vendor" : "Minstrel Silnon", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Purifying Rhythms" : {"Class" : "Bard", "Level" : "13", "Name" : "Purifying Rhythms", "Mana" : "0", "Skill" : "Percussion_instruments", "Target Type" : "Group", "Era" : "Classic", "PoK Vendor" : "Minstrel Cirsaelle", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Lyssa`s Cataloging Libretto" : {"Class" : "Bard", "Level" : "14", "Name" : "Lyssa`s Cataloging Libretto", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Single target", "Era" : "Classic", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "https://allaclone.wayfarershaven.com/?a=item&id=15737", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Kelin`s Lucid Lullaby" : {"Class" : "Bard", "Level" : "15", "Name" : "Kelin`s Lucid Lullaby", "Mana" : "0", "Skill" : "Stringed_instruments", "Target Type" : "Single target", "Era" : "Classic", "PoK Vendor" : "Minstrel Gwiar", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Song of Sustenance" : {"Class" : "Bard", "Level" : "15", "Name" : "Song of Sustenance", "Mana" : "0", "Skill" : "Stringed_instruments", "Target Type" : "Group", "Era" : "Luclin", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "https://allaclone.wayfarershaven.com/?a=item&id=7702", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Tarew`s Aquatic Ayre" : {"Class" : "Bard", "Level" : "16", "Name" : "Tarew`s Aquatic Ayre", "Mana" : "0", "Skill" : "Wind_instruments", "Target Type" : "Group", "Era" : "Classic", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "https://allaclone.wayfarershaven.com/?a=item&id=15729", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Guardian Rhythms" : {"Class" : "Bard", "Level" : "17", "Name" : "Guardian Rhythms", "Mana" : "0", "Skill" : "Percussion_instruments", "Target Type" : "Group", "Era" : "Classic", "PoK Vendor" : "Minstrel Cirsaelle", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Denon`s Disruptive Discord" : {"Class" : "Bard", "Level" : "18", "Name" : "Denon`s Disruptive Discord", "Mana" : "0", "Skill" : "Brass_instruments", "Target Type" : "Area of effect around the caster", "Era" : "Classic", "PoK Vendor" : "Minstrel Silnon", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Shauri`s Sonorous Clouding" : {"Class" : "Bard", "Level" : "19", "Name" : "Shauri`s Sonorous Clouding", "Mana" : "0", "Skill" : "Wind_instruments", "Target Type" : "Group", "Era" : "Classic", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "https://allaclone.wayfarershaven.com/?a=item&id=15719", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Cassindra`s Chant of Clarity" : {"Class" : "Bard", "Level" : "20", "Name" : "Cassindra`s Chant of Clarity", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Group", "Era" : "Velious", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "https://allaclone.wayfarershaven.com/?a=item&id=19504", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Largo`s Melodic Binding" : {"Class" : "Bard", "Level" : "20", "Name" : "Largo`s Melodic Binding", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Area of effect around the caster", "Era" : "Classic", "PoK Vendor" : "Minstrel Silnon", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Melanie`s Mellifluous Motion" : {"Class" : "Bard", "Level" : "21", "Name" : "Melanie`s Mellifluous Motion", "Mana" : "0", "Skill" : "Wind_instruments", "Target Type" : "Group", "Era" : "Classic", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "https://allaclone.wayfarershaven.com/?a=item&id=15739", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Alenia`s Disenchanting Melody" : {"Class" : "Bard", "Level" : "22", "Name" : "Alenia`s Disenchanting Melody", "Mana" : "0", "Skill" : "Stringed_instruments", "Target Type" : "Group", "Era" : "Classic", "PoK Vendor" : "Minstrel Cirsaelle", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Selo`s Consonant Chain" : {"Class" : "Bard", "Level" : "23", "Name" : "Selo`s Consonant Chain", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Single target", "Era" : "Classic", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "https://allaclone.wayfarershaven.com/?a=item&id=15738", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Lyssa`s Veracious Concord" : {"Class" : "Bard", "Level" : "24", "Name" : "Lyssa`s Veracious Concord", "Mana" : "0", "Skill" : "Wind_instruments", "Target Type" : "Group", "Era" : "Classic", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "https://allaclone.wayfarershaven.com/?a=item&id=15735", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Psalm of Warmth" : {"Class" : "Bard", "Level" : "25", "Name" : "Psalm of Warmth", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Group", "Era" : "Classic", "PoK Vendor" : "Minstrel Cirsaelle", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Selo's Rhythm of Speed" : {"Class" : "Bard", "Level" : "25", "Name" : "Selo's Rhythm of Speed", "Mana" : "0", "Skill" : "Percussion_instruments", "Target Type" : "Group", "Era" : "LDoN", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Angstlich`s Appalling Screech" : {"Class" : "Bard", "Level" : "26", "Name" : "Angstlich`s Appalling Screech", "Mana" : "0", "Skill" : "Brass_instruments", "Target Type" : "Area of effect around the caster", "Era" : "Classic", "PoK Vendor" : "Minstrel Gwiar", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Solon's Song of the Sirens" : {"Class" : "Bard", "Level" : "27", "Name" : "Solon's Song of the Sirens", "Mana" : "0", "Skill" : "Wind_instruments", "Target Type" : "Single target", "Era" : "Classic", "PoK Vendor" : "Minstrel Gwiar", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Crission`s Pixie Strike" : {"Class" : "Bard", "Level" : "28", "Name" : "Crission`s Pixie Strike", "Mana" : "0", "Skill" : "Wind_instruments", "Target Type" : "Single target", "Era" : "Classic", "PoK Vendor" : "Minstrel Gwiar", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Psalm of Vitality" : {"Class" : "Bard", "Level" : "29", "Name" : "Psalm of Vitality", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Group", "Era" : "Classic", "PoK Vendor" : "Minstrel Cirsaelle", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Amplification" : {"Class" : "Bard", "Level" : "30", "Name" : "Amplification", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Self only", "Era" : "Luclin", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "https://allaclone.wayfarershaven.com/?a=item&id=7703", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Fufil`s Curtailing Chant" : {"Class" : "Bard", "Level" : "30", "Name" : "Fufil`s Curtailing Chant", "Mana" : "0", "Skill" : "Percussion_instruments", "Target Type" : "Single target", "Era" : "Classic", "PoK Vendor" : "Minstrel Silnon", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Agilmente`s Aria of Eagles" : {"Class" : "Bard", "Level" : "31", "Name" : "Agilmente`s Aria of Eagles", "Mana" : "0", "Skill" : "Wind_instruments", "Target Type" : "Group", "Era" : "Classic", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "https://allaclone.wayfarershaven.com/?a=item&id=15718", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Cassindra`s Chorus of Clarity" : {"Class" : "Bard", "Level" : "32", "Name" : "Cassindra`s Chorus of Clarity", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Group", "Era" : "Classic", "PoK Vendor" : "Minstrel Cirsaelle", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Psalm of Cooling" : {"Class" : "Bard", "Level" : "33", "Name" : "Psalm of Cooling", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Group", "Era" : "Classic", "PoK Vendor" : "Minstrel Cirsaelle", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Cantata of Soothing" : {"Class" : "Bard", "Level" : "34", "Name" : "Cantata of Soothing", "Mana" : "0", "Skill" : "Stringed_instruments", "Target Type" : "Group", "Era" : "Velious", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "https://allaclone.wayfarershaven.com/?a=item&id=30448", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Lyssa`s Solidarity of Vision" : {"Class" : "Bard", "Level" : "34", "Name" : "Lyssa`s Solidarity of Vision", "Mana" : "0", "Skill" : "Wind_instruments", "Target Type" : "Single target", "Era" : "Classic", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "https://allaclone.wayfarershaven.com/?a=item&id=15721", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Denon`s Dissension" : {"Class" : "Bard", "Level" : "35", "Name" : "Denon`s Dissension", "Mana" : "0", "Skill" : "Brass_instruments", "Target Type" : "Area of effect around the caster", "Era" : "Classic", "PoK Vendor" : "Minstrel Silnon", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Vilia`s Verses of Celerity" : {"Class" : "Bard", "Level" : "36", "Name" : "Vilia`s Verses of Celerity", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Group", "Era" : "Classic", "PoK Vendor" : "Minstrel Silnon", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Psalm of Purity" : {"Class" : "Bard", "Level" : "37", "Name" : "Psalm of Purity", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Group", "Era" : "Classic", "PoK Vendor" : "Minstrel Cirsaelle", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Tuyen`s Chant of Flame" : {"Class" : "Bard", "Level" : "38", "Name" : "Tuyen`s Chant of Flame", "Mana" : "0", "Skill" : "Percussion_instruments", "Target Type" : "Single target", "Era" : "Classic", "PoK Vendor" : "Minstrel Silnon", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Katta's Song of Sword Dancing" : {"Class" : "Bard", "Level" : "39", "Name" : "Katta's Song of Sword Dancing", "Mana" : "0", "Skill" : "Percussion_instruments", "Target Type" : "Group", "Era" : "Luclin", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "https://allaclone.wayfarershaven.com/?a=item&id=7704", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Solon's Bewitching Bravura" : {"Class" : "Bard", "Level" : "39", "Name" : "Solon's Bewitching Bravura", "Mana" : "60", "Skill" : "Wind_instruments", "Target Type" : "Single target", "Era" : "Classic", "PoK Vendor" : "Minstrel Gwiar", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Sionachie`s Dreams" : {"Class" : "Bard", "Level" : "40", "Name" : "Sionachie`s Dreams", "Mana" : "0", "Skill" : "Wind_instruments", "Target Type" : "Single target", "Era" : "Classic", "PoK Vendor" : "Minstrel Gwiar", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Syvelian`s Anti-Magic Aria" : {"Class" : "Bard", "Level" : "40", "Name" : "Syvelian`s Anti-Magic Aria", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Single target", "Era" : "Classic", "PoK Vendor" : "Minstrel Gwiar", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Psalm of Mystic Shielding" : {"Class" : "Bard", "Level" : "41", "Name" : "Psalm of Mystic Shielding", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Group", "Era" : "Classic", "PoK Vendor" : "Minstrel Cirsaelle", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_McVaxius` Berserker Crescendo" : {"Class" : "Bard", "Level" : "42", "Name" : "McVaxius` Berserker Crescendo", "Mana" : "0", "Skill" : "Brass_instruments", "Target Type" : "Group", "Era" : "Classic", "PoK Vendor" : "Minstrel Silnon", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Tuyen`s Chant of Disease" : {"Class" : "Bard", "Level" : "42", "Name" : "Tuyen`s Chant of Disease", "Mana" : "0", "Skill" : "Percussion_instruments", "Target Type" : "Single target", "Era" : "Classic", "PoK Vendor" : "Minstrel Cirsaelle", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Denon`s Desperate Dirge" : {"Class" : "Bard", "Level" : "43", "Name" : "Denon`s Desperate Dirge", "Mana" : "800", "Skill" : "Singing", "Target Type" : "Area of effect around the target", "Era" : "Classic", "PoK Vendor" : "Minstrel Silnon", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Cassindra`s Elegy" : {"Class" : "Bard", "Level" : "44", "Name" : "Cassindra`s Elegy", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Group", "Era" : "Classic", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "https://allaclone.wayfarershaven.com/?a=item&id=15745", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Aria of Asceticism" : {"Class" : "Bard", "Level" : "45", "Name" : "Aria of Asceticism", "Mana" : "0", "Skill" : "Wind_instruments", "Target Type" : "Single target", "Era" : "Ykesha", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "https://everquest.allakhazam.com/db/quest.html?quest=2328", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Jonthan's Provocation" : {"Class" : "Bard", "Level" : "45", "Name" : "Jonthan's Provocation", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Self only", "Era" : "Classic", "PoK Vendor" : "Minstrel Silnon", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Tuyen`s Chant of Frost" : {"Class" : "Bard", "Level" : "46", "Name" : "Tuyen`s Chant of Frost", "Mana" : "0", "Skill" : "Percussion_instruments", "Target Type" : "Single target", "Era" : "Classic", "PoK Vendor" : "Minstrel Silnon", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Niv`s Melody of Preservation" : {"Class" : "Bard", "Level" : "47", "Name" : "Niv`s Melody of Preservation", "Mana" : "0", "Skill" : "Stringed_instruments", "Target Type" : "Group", "Era" : "Classic", "PoK Vendor" : "Minstrel Cirsaelle", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Selo`s Chords of Cessation" : {"Class" : "Bard", "Level" : "48", "Name" : "Selo`s Chords of Cessation", "Mana" : "0", "Skill" : "Stringed_instruments", "Target Type" : "Area of effect around the caster", "Era" : "Classic", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "https://allaclone.wayfarershaven.com/?a=item&id=15746", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Selo`s Accelerating Chorus" : {"Class" : "Bard", "Level" : "49", "Name" : "Selo`s Accelerating Chorus", "Mana" : "0", "Skill" : "Percussion_instruments", "Target Type" : "Group", "Era" : "Luclin", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "https://allaclone.wayfarershaven.com/?a=item&id=7705", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Shield of Songs" : {"Class" : "Bard", "Level" : "49", "Name" : "Shield of Songs", "Mana" : "0", "Skill" : "Stringed_instruments", "Target Type" : "Group", "Era" : "Velious", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "https://allaclone.wayfarershaven.com/?a=item&id=30450", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Melody of Ervaj" : {"Class" : "Bard", "Level" : "50", "Name" : "Melody of Ervaj", "Mana" : "0", "Skill" : "Brass_instruments", "Target Type" : "Group", "Era" : "Velious", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "https://allaclone.wayfarershaven.com/?a=item&id=30449", "Research URL" : ""}
,"Bard_Tuyen`s Chant of Poison" : {"Class" : "Bard", "Level" : "50", "Name" : "Tuyen`s Chant of Poison", "Mana" : "0", "Skill" : "Percussion_instruments", "Target Type" : "Single target", "Era" : "Classic", "PoK Vendor" : "Minstrel Cirsaelle", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Verses of Victory" : {"Class" : "Bard", "Level" : "50", "Name" : "Verses of Victory", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Group", "Era" : "Classic", "PoK Vendor" : "Minstrel Silnon", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Largo`s Absonant Binding" : {"Class" : "Bard", "Level" : "51", "Name" : "Largo`s Absonant Binding", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Single target", "Era" : "Kunark", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "https://allaclone.wayfarershaven.com/?a=item&id=19451", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Resistant Discipline" : {"Class" : "Bard", "Level" : "51", "Name" : "Resistant Discipline", "Mana" : "0", "Skill" : "Defense", "Target Type" : "Self only", "Era" : "n/a", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Selo`s Song of Travel" : {"Class" : "Bard", "Level" : "51", "Name" : "Selo`s Song of Travel", "Mana" : "0", "Skill" : "Percussion_instruments", "Target Type" : "Group", "Era" : "Kunark", "PoK Vendor" : "Minstrel Eoweril", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Aria of Innocence" : {"Class" : "Bard", "Level" : "52", "Name" : "Aria of Innocence", "Mana" : "0", "Skill" : "Wind_instruments", "Target Type" : "Single target", "Era" : "Ykesha", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "https://everquest.allakhazam.com/db/quest.html?quest=2388", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Battlecry of the Vah Shir" : {"Class" : "Bard", "Level" : "52", "Name" : "Battlecry of the Vah Shir", "Mana" : "0", "Skill" : "Brass_instruments", "Target Type" : "Group", "Era" : "Luclin", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "https://allaclone.wayfarershaven.com/?a=item&id=7706", "Research URL" : ""}
,"Bard_Nillipus` March of the Wee" : {"Class" : "Bard", "Level" : "52", "Name" : "Nillipus` March of the Wee", "Mana" : "0", "Skill" : "Percussion_instruments", "Target Type" : "Group", "Era" : "Kunark", "PoK Vendor" : "Minstrel Eoweril", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Song of Dawn" : {"Class" : "Bard", "Level" : "53", "Name" : "Song of Dawn", "Mana" : "0", "Skill" : "Wind_instruments", "Target Type" : "Single target", "Era" : "Kunark", "PoK Vendor" : "Minstrel Eoweril", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Song of Twilight" : {"Class" : "Bard", "Level" : "53", "Name" : "Song of Twilight", "Mana" : "0", "Skill" : "Wind_instruments", "Target Type" : "Single target", "Era" : "Kunark", "PoK Vendor" : "Minstrel Eoweril", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "https://allaclone.wayfarershaven.com/?a=item&id=7707", "Research URL" : ""}
,"Bard_Elemental Chorus" : {"Class" : "Bard", "Level" : "54", "Name" : "Elemental Chorus", "Mana" : "0", "Skill" : "Percussion_instruments", "Target Type" : "Friendly area of effect", "Era" : "Luclin", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "https://allaclone.wayfarershaven.com/?a=item&id=7707", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Fearless Discipline" : {"Class" : "Bard", "Level" : "54", "Name" : "Fearless Discipline", "Mana" : "0", "Skill" : "Defense", "Target Type" : "Self only", "Era" : "n/a", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Selo`s Assonant Strain" : {"Class" : "Bard", "Level" : "54", "Name" : "Selo`s Assonant Strain", "Mana" : "0", "Skill" : "Stringed_instruments", "Target Type" : "Area of effect around the caster", "Era" : "Kunark", "PoK Vendor" : "Minstrel Eoweril", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Vilia`s Chorus of Celerity" : {"Class" : "Bard", "Level" : "54", "Name" : "Vilia`s Chorus of Celerity", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Group", "Era" : "Kunark", "PoK Vendor" : "Minstrel Eoweril", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Aura of Insight" : {"Class" : "Bard", "Level" : "55", "Name" : "Aura of Insight", "Mana" : "0", "Skill" : "Brass_instruments", "Target Type" : "Self only", "Era" : "PoR", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Brusco`s Bombastic Bellow" : {"Class" : "Bard", "Level" : "55", "Name" : "Brusco`s Bombastic Bellow", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Single target", "Era" : "Kunark", "PoK Vendor" : "Minstrel Eoweril", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Cantata of Replenishment" : {"Class" : "Bard", "Level" : "55", "Name" : "Cantata of Replenishment", "Mana" : "0", "Skill" : "Stringed_instruments", "Target Type" : "Group", "Era" : "Kunark", "PoK Vendor" : "Minstrel Eoweril", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Deftdance Discipline" : {"Class" : "Bard", "Level" : "55", "Name" : "Deftdance Discipline", "Mana" : "0", "Skill" : "Defense", "Target Type" : "Self only", "Era" : "n/a", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Occlusion of Sound" : {"Class" : "Bard", "Level" : "55", "Name" : "Occlusion of Sound", "Mana" : "0", "Skill" : "Percussion_instruments", "Target Type" : "Single target", "Era" : "Velious", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "https://allaclone.wayfarershaven.com/?a=item&id=30451", "Research URL" : ""}
,"Bard_Purifying Chorus" : {"Class" : "Bard", "Level" : "56", "Name" : "Purifying Chorus", "Mana" : "0", "Skill" : "Percussion_instruments", "Target Type" : "Friendly area of effect", "Era" : "Luclin", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "https://allaclone.wayfarershaven.com/?a=item&id=7708", "Research URL" : ""}
,"Bard_Song of Highsun" : {"Class" : "Bard", "Level" : "56", "Name" : "Song of Highsun", "Mana" : "0", "Skill" : "Wind_instruments", "Target Type" : "Single target", "Era" : "Kunark", "PoK Vendor" : "Minstrel Eoweril", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Song of Midnight" : {"Class" : "Bard", "Level" : "56", "Name" : "Song of Midnight", "Mana" : "0", "Skill" : "Brass_instruments", "Target Type" : "Area of effect around the caster", "Era" : "Kunark", "PoK Vendor" : "Minstrel Eoweril", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Cassindra's Insipid Ditty" : {"Class" : "Bard", "Level" : "57", "Name" : "Cassindra's Insipid Ditty", "Mana" : "0", "Skill" : "Stringed_instruments", "Target Type" : "Single target", "Era" : "Kunark", "PoK Vendor" : "Minstrel Eoweril", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_McVaxius` Rousing Rondo" : {"Class" : "Bard", "Level" : "57", "Name" : "McVaxius` Rousing Rondo", "Mana" : "0", "Skill" : "Brass_instruments", "Target Type" : "Group", "Era" : "Kunark", "PoK Vendor" : "Minstrel Eoweril", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Chorus of Replenishment" : {"Class" : "Bard", "Level" : "58", "Name" : "Chorus of Replenishment", "Mana" : "0", "Skill" : "Stringed_instruments", "Target Type" : "Friendly area of effect", "Era" : "Luclin", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "https://allaclone.wayfarershaven.com/?a=item&id=7709", "Research URL" : ""}
,"Bard_Dreams of Ayonae" : {"Class" : "Bard", "Level" : "58", "Name" : "Dreams of Ayonae", "Mana" : "0", "Skill" : "Wind_instruments", "Target Type" : "Single target", "Era" : "Luclin", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "https://allaclone.wayfarershaven.com/?a=item&id=24548", "Research URL" : ""}
,"Bard_Jonthan's Inspiration" : {"Class" : "Bard", "Level" : "58", "Name" : "Jonthan's Inspiration", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Self only", "Era" : "Kunark", "PoK Vendor" : "Minstrel Eoweril", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Niv`s Harmonic" : {"Class" : "Bard", "Level" : "58", "Name" : "Niv`s Harmonic", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Group", "Era" : "Kunark", "PoK Vendor" : "Minstrel Eoweril", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Denon`s Bereavement" : {"Class" : "Bard", "Level" : "59", "Name" : "Denon`s Bereavement", "Mana" : "0", "Skill" : "Stringed_instruments", "Target Type" : "Area of effect around the caster", "Era" : "Kunark", "PoK Vendor" : "Minstrel Eoweril", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Solon's Charismatic Concord" : {"Class" : "Bard", "Level" : "59", "Name" : "Solon's Charismatic Concord", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Group", "Era" : "Kunark", "PoK Vendor" : "Minstrel Eoweril", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Ancient: Lcea's Lament" : {"Class" : "Bard", "Level" : "60", "Name" : "Ancient: Lcea's Lament", "Mana" : "0", "Skill" : "Stringed_instruments", "Target Type" : "Friendly area of effect", "Era" : "Luclin", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "https://allaclone.wayfarershaven.com/?a=item&id=26622", "Research URL" : ""}
,"Bard_Ancient: Lullaby of Shadow" : {"Class" : "Bard", "Level" : "60", "Name" : "Ancient: Lullaby of Shadow", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Single target", "Era" : "Luclin", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "https://allaclone.wayfarershaven.com/?a=item&id=26623", "Research URL" : ""}
,"Bard_Angstlich's Assonance" : {"Class" : "Bard", "Level" : "60", "Name" : "Angstlich's Assonance", "Mana" : "0", "Skill" : "Brass_instruments", "Target Type" : "Single target", "Era" : "Kunark", "PoK Vendor" : "Minstrel Eoweril", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Composition of Ervaj" : {"Class" : "Bard", "Level" : "60", "Name" : "Composition of Ervaj", "Mana" : "0", "Skill" : "Brass_instruments", "Target Type" : "Group", "Era" : "Velious", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "https://allaclone.wayfarershaven.com/?a=item&id=30452", "Research URL" : ""}
,"Bard_Ervaj's Lost Composition" : {"Class" : "Bard", "Level" : "60", "Name" : "Ervaj's Lost Composition", "Mana" : "0", "Skill" : "Brass_instruments", "Target Type" : "Single target", "Era" : "Luclin", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "https://allaclone.wayfarershaven.com/?a=item&id=30479", "Research URL" : ""}
,"Bard_Kazumi's Note of Preservation" : {"Class" : "Bard", "Level" : "60", "Name" : "Kazumi's Note of Preservation", "Mana" : "0", "Skill" : "Wind_instruments", "Target Type" : "Group", "Era" : "Kunark", "PoK Vendor" : "Minstrel Eoweril", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Puretone Discipline" : {"Class" : "Bard", "Level" : "60", "Name" : "Puretone Discipline", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Self only", "Era" : "n/a", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Warsong of the Vah Shir" : {"Class" : "Bard", "Level" : "60", "Name" : "Warsong of the Vah Shir", "Mana" : "0", "Skill" : "Brass_instruments", "Target Type" : "Group", "Era" : "Luclin", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "https://allaclone.wayfarershaven.com/?a=item&id=7710", "Research URL" : ""}
,"Bard_Saryrn's Scream of Pain" : {"Class" : "Bard", "Level" : "61", "Name" : "Saryrn's Scream of Pain", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Single target", "Era" : "PoP", "PoK Vendor" : "Minstrel Cirsaelle", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Silent Song of Quellious" : {"Class" : "Bard", "Level" : "61", "Name" : "Silent Song of Quellious", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Single target", "Era" : "PoP", "PoK Vendor" : "", "Turn In" : "Minstrel Eoweril: Ethereal Parchment", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Song of the Storm" : {"Class" : "Bard", "Level" : "61", "Name" : "Song of the Storm", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Group teleport", "Era" : "DoN", "PoK Vendor" : "", "Turn In" : "", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Tuyen`s Chant of the Plague" : {"Class" : "Bard", "Level" : "61", "Name" : "Tuyen`s Chant of the Plague", "Mana" : "0", "Skill" : "Percussion_instruments", "Target Type" : "Single target", "Era" : "PoP", "PoK Vendor" : "", "Turn In" : "Minstrel Eoweril: Ethereal Parchment", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Angstlich's Echo of Terror" : {"Class" : "Bard", "Level" : "62", "Name" : "Angstlich's Echo of Terror", "Mana" : "0", "Skill" : "Brass_instruments", "Target Type" : "Area of effect around the caster", "Era" : "PoP", "PoK Vendor" : "", "Turn In" : "Minstrel Eoweril: Ethereal Parchment", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Dreams of Thule" : {"Class" : "Bard", "Level" : "62", "Name" : "Dreams of Thule", "Mana" : "0", "Skill" : "Wind_instruments", "Target Type" : "Single target", "Era" : "PoP", "PoK Vendor" : "", "Turn In" : "Minstrel Eoweril: Ethereal Parchment", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Druzzil's Disillusionment" : {"Class" : "Bard", "Level" : "62", "Name" : "Druzzil's Disillusionment", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Single target", "Era" : "PoP", "PoK Vendor" : "", "Turn In" : "Minstrel Eoweril: Ethereal Parchment", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Melody of Mischief" : {"Class" : "Bard", "Level" : "62", "Name" : "Melody of Mischief", "Mana" : "0", "Skill" : "Stringed_instruments", "Target Type" : "Area of effect around the caster", "Era" : "PoP", "PoK Vendor" : "", "Turn In" : "Minstrel Eoweril: Ethereal Parchment", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Warsong of Zek" : {"Class" : "Bard", "Level" : "62", "Name" : "Warsong of Zek", "Mana" : "0", "Skill" : "Brass_instruments", "Target Type" : "Group", "Era" : "PoP", "PoK Vendor" : "", "Turn In" : "Minstrel Eoweril: Ethereal Parchment", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Wind of Marr" : {"Class" : "Bard", "Level" : "62", "Name" : "Wind of Marr", "Mana" : "0", "Skill" : "Stringed_instruments", "Target Type" : "Group teleport", "Era" : "PoP", "PoK Vendor" : "", "Turn In" : "Minstrel Eoweril: Ethereal Parchment", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Psalm of Veeshan" : {"Class" : "Bard", "Level" : "63", "Name" : "Psalm of Veeshan", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Group", "Era" : "PoP", "PoK Vendor" : "", "Turn In" : "Minstrel Eoweril: Spectral Parchment", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Tuyen`s Chant of Ice" : {"Class" : "Bard", "Level" : "63", "Name" : "Tuyen`s Chant of Ice", "Mana" : "0", "Skill" : "Percussion_instruments", "Target Type" : "Single target", "Era" : "PoP", "PoK Vendor" : "", "Turn In" : "Minstrel Eoweril: Spectral Parchment", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Tuyen`s Chant of Venom" : {"Class" : "Bard", "Level" : "63", "Name" : "Tuyen`s Chant of Venom", "Mana" : "0", "Skill" : "Percussion_instruments", "Target Type" : "Single target", "Era" : "PoP", "PoK Vendor" : "", "Turn In" : "Minstrel Eoweril: Spectral Parchment", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Call of the Banshee" : {"Class" : "Bard", "Level" : "64", "Name" : "Call of the Banshee", "Mana" : "90", "Skill" : "Wind_instruments", "Target Type" : "Single target", "Era" : "PoP", "PoK Vendor" : "", "Turn In" : "Minstrel Eoweril: Spectral Parchment", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Chorus of Marr" : {"Class" : "Bard", "Level" : "64", "Name" : "Chorus of Marr", "Mana" : "0", "Skill" : "Stringed_instruments", "Target Type" : "Friendly area of effect", "Era" : "PoP", "PoK Vendor" : "", "Turn In" : "Minstrel Eoweril: Spectral Parchment", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Dreams of Terris" : {"Class" : "Bard", "Level" : "64", "Name" : "Dreams of Terris", "Mana" : "0", "Skill" : "Wind_instruments", "Target Type" : "Single target", "Era" : "PoP", "PoK Vendor" : "", "Turn In" : "Minstrel Eoweril: Spectral Parchment", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Requiem of Time" : {"Class" : "Bard", "Level" : "64", "Name" : "Requiem of Time", "Mana" : "0", "Skill" : "Brass_instruments", "Target Type" : "Single target", "Era" : "PoP", "PoK Vendor" : "", "Turn In" : "Minstrel Eoweril: Spectral Parchment", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Rizlona's Call of Flame" : {"Class" : "Bard", "Level" : "64", "Name" : "Rizlona's Call of Flame", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Group teleport", "Era" : "PoP", "PoK Vendor" : "", "Turn In" : "Minstrel Eoweril: Spectral Parchment", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Harmony of Sound" : {"Class" : "Bard", "Level" : "65", "Name" : "Harmony of Sound", "Mana" : "0", "Skill" : "Percussion_instruments", "Target Type" : "Single target", "Era" : "PoP", "PoK Vendor" : "", "Turn In" : "Minstrel Eoweril: Glyphed Rune Word", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Lullaby of Morell" : {"Class" : "Bard", "Level" : "65", "Name" : "Lullaby of Morell", "Mana" : "0", "Skill" : "Singing", "Target Type" : "Single target", "Era" : "PoP", "PoK Vendor" : "", "Turn In" : "Minstrel Eoweril: Glyphed Rune Word", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}
,"Bard_Tuyen`s Chant of Fire" : {"Class" : "Bard", "Level" : "65", "Name" : "Tuyen`s Chant of Fire", "Mana" : "0", "Skill" : "Percussion_instruments", "Target Type" : "Single target", "Era" : "PoP", "PoK Vendor" : "", "Turn In" : "Minstrel Eoweril: Glyphed Rune Word", "Vendor URL" : "", "Quest URL" : "", "Drop  URL" : "", "Research URL" : ""}

    }